export const MAIN_ROUTE = '/'
export const APPLIC_ROUTE = '/application'
export const PROFILE_ROUTE = '/profile'
export const APPLICTEXT_ROUTE = '/applicationText'
export const MYAPPLIC_ROUTE = '/myapplic'
export const CHAT_ROUTE = '/chat'